---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: lab
runtimeConfig:
  "api/alpha": false

networking:
  disableDefaultCNI: true
  kubeProxyMode: ipvs
  ipFamily: ipv4
  apiServerAddress: 172.16.252.3
  apiServerPort: 6443
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"

nodes:
  - role: control-plane
  - role: worker
  - role: worker
  - role: worker